# 异常 exception

目前一个基本的结构是有了，我们还需要错误处理机制，exception，接下来我们就来添加错误处理

- Default.exception.ts
- RouteBase 里面中间件添加 responseHandler，负责控制器的错误处理，避免每次都 try...catch

## 目录结构

```
- src
  - bases
    - route.base.ts
    - controller.base.ts
  - common
    - response
      - response.object.ts
  - exceptions
    - default.exception.ts  // 默认错误处理
  - main
    - api
      - todo
        - todo.route.ts
        - todo.controller.ts
      - api.route.ts
  - types
    - httpStatus.type.ts
  - app.route.ts
  - app.ts
  - index.ts
- package.json
- tsconfig.json
```

## DefaultException

`exceptions/default.exception.ts`

```ts
import { ErrorRequestHandler } from "express";

export const DefaultException: ErrorRequestHandler = (err, req, res, next) => {
  // 默认异常处理，err是经过处理的参数，格式为：{status: 500, message:'', data:null}
  res.status(err.status).json(err);
};
```

## App 添加错误处理中间件方法

```ts
import express, { ErrorRequestHandler } from "express";

export class App {
  // ...

  public setException(handler: ErrorRequestHandler) {
    this.app.use(handler);
  }

  // ...
}
```

`index.ts`

```ts
import { App } from "./app";
import { DefaultException } from "./exceptions/default.exception";

const bootstrap = () => {
  const app = new App();
  app.setException(DefaultException);
  app.bootstrap();
};

bootstrap();
```

## RouteBase

`bases/route.base.ts`，添加一个`responseHandler`方法

```ts
 // 异常处理包裹层，避免每次处理异常都要try...catch
  /**
   *
   * @param method 控制器处理函数，也就是包裹的controller函数，返回一个Promise<ResponseObject>
   * @param controller 控制器，
   */
  protected responseHandler(
    method: IResponseHanlder,
    controller = this.controller
  ) {
    // 返回一个处理请求函数，把上一层的参数传递到最里面
    return (req: Request, res: Response, next: NextFunction) =>
      // 里面执行我们的包裹函数，通过call来指定this
      // method是一个promise，我们就可以处理成功，或者错误的情况了
      method
        .call(controller, req, res, next)
        .then((obj) => res.status(obj.status).json(obj))
        .catch((err) =>
          next(
            this.controller.formatResponse(
              err.message,
              err.status || HttpStatus.INTERNAL_ERROR
            )
          )
        );
  }
```

## 修改 TodoController

```ts
public async getTodos(req: Request, res: Response, next: NextFunction) {
  // 测试错误的情况，走默认错误处理
  // const a = new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     reject({ status: 600, message: "hello" });
  //   }, 1000);
  // });

  // await a;


  const obj = this.formatResponse([], HttpStatus.OK);
  return obj;
}
```

## 修改 TodoRoute

```ts
import { RouteBase } from "../../../bases/route.base";
import { TodoController } from "./todo.contoller";

export class TodoRoute extends RouteBase {
  protected controller!: TodoController;

  protected registerRoute(): void {
    this.controller = new TodoController();
    this.router.get("/", this.responseHandler(this.controller.getTodos));
  }
}
```

这样就构建好了包含错误处理机制的 express 应用，我们在 controller 里面写代码的时候，就不需要每次都 try...catch，因为已经包含在了 Route 里面帮我们做了这一切，接下来就是我们和数据库打交道的时候了，MVC 中的 M（Model）即将登场
